title: my-jekyll-theme
# title: Wannabee
# TODO: come up with a cool name. naming things is hard bcoz all of the cool names are taken already...

# author: Keith A. Smith

description: "a really cool jekyll theme..."
# description: "Wannabee is a retro and anachronistic Jekyll theme"

encoding: utf-8

exclude: ["README.md", "LICENSE", "*.gem", "*.gemspec", "Gemfile.lock"]
